trigger:
- master

variables:
- group: ansible

stages:
- stage: CI
  pool: Default
  jobs:
  - job: publish_artifact
    steps:

    - script: npm install
      displayName: install npm packages
    
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/zippedApp.zip'
        replaceExistingArchive: true
    
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/zippedApp.zip'
        artifactType: 'pipeline'
        artifactName: 'zipped'

- stage: CD_staging
  jobs:
  - deployment: staging
    displayName: staging
    environment: 'staging.stg-ansibleVM'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: tools/ansible.yml
            parameters:
              pghost: $(stg_pghost)
              pg_username: $(pg_username)
              pg_password: $(pg_password)
              LB_ip: $(stg_LB_ip)
              okta_url: $(okta_url)
              okta_client_id: $(okta_client_id)
              okta_client_secret: $(okta_client_secret)
              servers_username: $(servers_username) 
              servers_ssh_pass: $(servers_ssh_pass)
              hosts:
              - 10.0.1.4
              - 10.0.1.5


- stage: CD_production
  jobs:
  - deployment: DeployWeb
    displayName: deploy Web App
    environment: 'deployment.prd-ansibleVM'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: tools/ansible.yml
            parameters:
              pghost: $(prd_pghost)
              pg_username: $(pg_username)
              pg_password: $(pg_password)
              LB_ip: $(prd_LB_ip)
              okta_url: $(okta_url)
              okta_client_id: $(okta_client_id)
              okta_client_secret: $(okta_client_secret)
              servers_username: $(servers_username) 
              servers_ssh_pass: $(servers_ssh_pass)
              hosts:
              - 10.0.1.4
              - 10.0.1.5
              - 10.0.1.6