name: Docker pipelin

trigger:
- master
- feature/*

pool: default

variables: 
- group: "env file"

stages:

# Continuous Integration Process
- stage: CI
  jobs:
  - job: BuildAndPushDocker
    workspace: 
      clean: all
    steps:
    # - script: docker rmi "docker pipeline"
    #   displayName: "remove previous docker images"
    
    - script: |
        Write-Host @"
        # Host configuration
        PORT=8080
        HOST=0.0.0.0
        # Postgres configuration
        PGHOST=$(stg_pghost)
        PGUSERNAME=$(pg_username)
        PGDATABASE=postgres
        PGPASSWORD=$(pg_password)
        PGPORT=5432
        HOST_URL=http://$(stg_LB_ip):8080
        COOKIE_ENCRYPT_PWD=superAwesomePasswordStringThatIsAtLeast32CharactersLong!
        NODE_ENV=development
        # Okta configuration
        OKTA_ORG_URL=$(okta_url)
        OKTA_CLIENT_ID=$(okta_client_id)
        OKTA_CLIENT_SECRET=$(okta_client_secret)
        "@ | Out-File -FilePath .\.env
      displayName: add .env file

    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: "docker pipeline"
        command: build
        Dockerfile: Dockerfile

# # Continuous Deployment Process for Staging Environment
# - stage: DeployToStaging
#   condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
#   jobs:
#   - deployment: staging
#     displayName: Deploy to Staging
#     environment:
#       name: <<YOUR ENVIRONMENT NAME>>
#       resourceType: VirtualMachine
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - <<YOUR TASKS>>
          
# # Continuous Delivery Process for Production Environment
# - stage: DeployToProduction
  # condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  # jobs:
  # - deployment: production
  #   displayName: Deploy to Production
  #   environment:
  #     name: <<YOUR ENVIRONMENT NAME>>
  #     resourceType: VirtualMachine
  #   strategy:
  #     runOnce:
  #       deploy:
  #         steps:
  #         - <<YOUR TASKS>>