name: Docker pipelin

trigger:
- master
- feature/*

pool: default

stages:

# Continuous Integration Process
- stage: CI
  jobs:
  - job: BuildAndPushDocker
    workspace: 
      clean: all
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: "docker pipeline"
        command: build
        Dockerfile: Dockerfile

# # Continuous Deployment Process for Staging Environment
# - stage: DeployToStaging
#   condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
#   jobs:
#   - deployment: staging
#     displayName: Deploy to Staging
#     environment:
#       name: <<YOUR ENVIRONMENT NAME>>
#       resourceType: VirtualMachine
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - <<YOUR TASKS>>
          
# # Continuous Delivery Process for Production Environment
# - stage: DeployToProduction
  # condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  # jobs:
  # - deployment: production
  #   displayName: Deploy to Production
  #   environment:
  #     name: <<YOUR ENVIRONMENT NAME>>
  #     resourceType: VirtualMachine
  #   strategy:
  #     runOnce:
  #       deploy:
  #         steps:
  #         - <<YOUR TASKS>>